config/routes.rb
Rails.application.routes.draw do

  get 'votes/new'

  get 'votes/create'
 
devise_for :users
root to: "questions#index"
 get 'questions/upvote'
 get 'questions/downvote'
 get 'answers/upvote'
 get 'answers/downvote'
resources :questions do
  resources :answers do
    resources :votes
  end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :question_tags, dependent: :destroy
  has_many :tags, through: :question_tags
  acts_as_votable



  def self.search(search)
    if search
      where('title LIKE ?', "%#{search}%")
    else
      []
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy,:upvote,:downvote]
 
  before_action :authenticate_user!, only: [:new]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all.sort_by{|question| question.vote_count}.reverse
    @lastquestions = Question.all.reverse
    @tags = Tag.all
    @findQuestions = Question.search(params[:search])
    @tagQuestions = Tag.find_by(name:params[:search])
    respond_to do |format|
      format.html { render :index }
      format.json { render jsonapi: @questions}
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @answers = @question.answers.all.sort_by{|answer| answer.vote_count}.reverse
    @answer = Answer.new
    # @tags = question.tags
    @vote = Vote.find_by({votable_type: "Question",votable_id: @question.id,voter_id:current_user.id}) if(current_user)
    if(@vote)
      if(@vote.vote_flag)
        @td_class = 'far'
        @tu_class = 'fas'
      else 
        @td_class = 'fas'
        @tu_class = 'far'
      end
    else
    
      @td_class = 'far'
      @tu_class = 'far'
    end
    @question_votes = Vote.where({votable_type: :Question, votable_id:@question.id})
    @question_votes = @question_votes.select{|vote| vote.vote_flag}.size - @question_votes.select{|vote| !vote.vote_flag}.size
    respond_to do |format|
      format.html { render :show }
      format.json { render jsonapi: @question}
  
  end
end
  # GET /questions/new
  def new
    # @tags = Tag.all
    @questiontag = QuestionTag.new
    @question = Question.new
    # render :layout => 'special_layout'
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params.merge!({user_id:current_user.id}))
    
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
         params[:question][:question_tag][:tag_id].each do |id| 
          if id.present?
            @questiontag = QuestionTag.create(question_id:@question.id, tag_id:id)
          end
        end
        puts params
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end
  

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def upvote
    @vote=Vote.find_by({votable_type:"Question",votable_id:@question.id,voter_id:current_user.id}) if current_user
    if !@vote  && current_user
      current_user.likes @question
    elsif(@vote)
      if(@vote.vote_flag)
        @vote.destroy
      else
        @vote.update(vote_flag: true)
      end
    end
    
    redirect_to question_path(@question)
  end

  def downvote
      @vote=Vote.find_by({votable_type:"Question",votable_id:@question.id,voter_id:current_user.id}) if current_user
      if !@vote  && current_user
        current_user.dislikes @question
      elsif(@vote)
        if(!@vote.vote_flag)
          @vote.destroy
        else
          @vote.update(vote_flag:false)
        end
      end 
       
      redirect_to question_path(@question)
end 
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :body, tag_id: [])
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.haml
= form_for @question do |f|
  - if @question.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      %ul
        - @question.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :título, class: 'font-weight-bold'
    = f.text_field :title, :required => true, placeholder:"¿Cuál es tú pregunta? Sé específico", id: "title", class: 'form-control'
  .field.mt-4
    = f.label :redacta_tu_pregunta_aquí, class: 'font-weight-bold'
    = f.trix_editor :body, :required => true, rows: "10",id: 'body', class: 'form-control ', "trix-change":"a"
    %button.btn.btn-info.btn-sm{"data-target" => "#myModal", "data-toggle" => "modal", :type => "button"} html preview
  .field.mt-4
    = f.label :etiquetas, class: 'font-weight-bold'
    .tagss
      = f.fields_for @questiontag do |qt|
        = qt.collection_select :tag_id, Tag.all, :id, :name, {}, {multiple: true, class:"form-control tagss"}
  .actions.mt-4
    = f.submit 'Publicar tu pregunta', class:'btn btn-success'
    .container
      / Trigger the modal with a button
      / Modal
      #myModal.modal.fade{:role => "dialog"}
        .modal-dialog.modal-lg
          .modal-content
            .modal-header
              %h4.modal-title Escriba su codigo html y css
            .modal-body          
              .main
                .header
                .menu
                .content
                .row
                  .col-6
                    %textarea#editor
                      :preserve
                  .col-6
                    %iframe#browser
            .modal-footer
              %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
              .row
                .col-12.text-right
                  %input{:onclick => "myTRY()", :type => "button",:id => "envivo", :value => "RUN", :class => "btn-success border-radius:30px"}/
    

app/views/questions/_formanswer.html.haml
= form_for [@question, @answer] do |f|
	- if @answer.errors.any?
		#error_explanation
			%h2= "#{pluralize(@answer.errors.count, "error")} prohibited this answer from being saved:"
			%ul
				- @answer.errors.full_messages.each do |message|
					%li= message
	.field.border-bottom.pb-5 
		= f.trix_editor :body, rows:"50", class: 'form-control '
	.actions.mt-4.text-center
		= f.submit 'Publicar respuesta',class:'btn btn-success'

app/views/questions/_formvotes.html.haml
= form_for [@question,@vote], url: url, method: method, remote:true do |f|
	-# - if @answer.errors.any?
	-# 	#error_explanation
	-# 		%h2= "#{pluralize(@answer.errors.count, "error")} prohibited this answer from being saved:"
	-# 		%ul
	-# 			- @answer.errors.full_messages.each do |message|
	-# 				%li= message
	.field.border-bottom.pb-5 
		-# =f.check_box :selection, {:checked_value => 1, :unchecked_value => 0 ,checked: true}
		=f.hidden_field :selection, value:1 
	.actions.mt-4.text-center
		= button_tag(type: "submit", class: "btn btn-default blue") do
			= fa_icon "thumbs-up"
= form_for [@question,@vote], url: url, method: method, remote:true  do |f|
	-# - if @answer.errors.any?
	-# 	#error_explanation
	-# 		%h2= "#{pluralize(@answer.errors.count, "error")} prohibited this answer from being saved:"
	-# 		%ul
	-# 			- @answer.errors.full_messages.each do |message|
	-# 				%li= message
	.field.border-bottom.pb-5 
		-# =f.check_box :selection, {:checked_value => 1, :unchecked_value => 0 ,checked: true}
		=f.hidden_field :selection, value:0 
	.actions.mt-4.text-center
		= button_tag(type: "submit", class: "btn btn-default blue") do
			= fa_icon "thumbs-down"
			

app/views/questions/edit.html.haml
%h1 Editing question

    
= render 'form'




= link_to 'Show', @question
\|
= link_to 'Back', questions_path

app/views/questions/index.html.haml
-# .container 
-#   .row.mt-4
-#     - @questions.each do |question|   
-#       .col-1.card
-#         .row.pt-2
-#           %strong
-#             Votos
-#         .row.pt-2
-#           %h3.text-secondary
-#             = @question_votes 
-#       .col-1
-#         .row.pt-2
-#           %strong
-#             Respuestas
-#         .row.pt-2
-#           %h3.text-secondary
-#             = question.answers.length
-#       .col-10
-#         %p=link_to question.title, question 
-#         %p= "Preguntado #{time_ago_in_words(question.created_at.utc.to_i)} por #{question.user.first_name} #{question.user.last_name}"
-#         - 0.upto(question.question_tags.size){|index|
-#         -  if index>3
-#           - break  
-#         -  elsif(question.question_tags[index]!=nil)
-#           %span=question.question_tags[index].tag.name
-#         - }

.container
  -if @tagQuestions != nil && @tagQuestions.question != []
    .row.mt-5
      .col-1
      .col-3.text-center.pr-0
        .card.text-white#popular
          %h5.mt-1.font-weight-bold
            Resultados de la búsqueda
    .row.justify-content-center
      .col-10
        %table.table.table-bordered#popularquestions.bg-white
          %thead
            %tr.text-center
              %td.font-weight-bold Votos
              %td.font-weight-bold Respuestas
              %td.font-weight-bold Título de la pregunta
          %tbody
            - @tagQuestions.question.each do |question|
              %tr
                -if question.vote_count < 0
                  %td.align-middle.text-center.bg-danger
                    %h3.text-white
                      = question.vote_count
                -elsif question.vote_count > 0
                  %td.align-middle.text-center.bg-success
                    %h3.text-white
                      = question.vote_count
                - else
                  %td.align-middle.text-center
                    %h3.text-secondary
                      = question.vote_count
                %td.align-middle.text-center
                  %h3.text-secondary
                    = question.answers.length
                %td
                  %h5
                    =link_to truncate(question.title, length:70), question
                  %p.text-right= "Hace #{time_ago_in_words(question.created_at.utc.to_i)} por #{question.user.first_name} #{question.user.last_name}"
                  - 0.upto(question.question_tags.size)  {|index|
                  -  if index>6
                    - break  
                  -  elsif(question.question_tags[index]!=nil)
                    %span.text-primary.tagstyle.p-1.mr-1
                      =question.question_tags[index].tag.name
                  - }
  -elsif params[:search] == nil
    .row.mt-5
      .col-1
      .col-2.text-center.pr-0
        .card.text-white#popular
          %h5.mt-1.font-weight-bold
            Populares
      .col-2.text-center.pl-0
        .card.text-white#last
          %h5.mt-1.font-weight-bold
            Recientes
    .row.justify-content-center
      .col-10
        %table.table.table-bordered#popularquestions.bg-white
          %thead
            %tr.text-center
              %td.font-weight-bold Votos
              %td.font-weight-bold Respuestas
              %td.font-weight-bold Título de la pregunta
          %tbody
            - @questions.each do |question|
              -@question_votes = Vote.where({votable_type: :Question, votable_id:question.id})
              -@question_votes = @question_votes.select{|vote| vote.vote_flag}.size - @question_votes.select{|vote| !vote.vote_flag}.size
              %tr
                -if question.vote_count < 0
                  %td.align-middle.text-center.bg-danger
                    %h3.text-white
                      = question.vote_count
                -elsif question.vote_count > 0
                  %td.align-middle.text-center.bg-success
                    %h3.text-white
                      = question.vote_count
                - else
                  %td.align-middle.text-center
                    %h3.text-secondary
                      = question.vote_count
                %td.align-middle.text-center
                  %h3.text-secondary
                    = question.answers.length
                %td
                  %h5
                    =link_to truncate(question.title, length:70), question
                  %p.text-right= "Hace #{time_ago_in_words(question.created_at.utc.to_i)} por #{question.user.first_name} #{question.user.last_name}"
                  - 0.upto(question.question_tags.size)  {|index|
                  -  if index>6
                    - break  
                  -  elsif(question.question_tags[index]!=nil)
                    %span.text-primary.tagstyle.p-1.mr-1
                      =question.question_tags[index].tag.name
                  - }
        %table.table.table-bordered#lastquestions.bg-white
          %thead
            %tr.text-center
              %td.font-weight-bold Votos
              %td.font-weight-bold Respuestas
              %td.font-weight-bold Título de la pregunta
          %tbody
            - @lastquestions.each do |question|
              %tr
                -if question.vote_count < 0
                  %td.align-middle.text-center.bg-danger
                    %h3.text-white
                      = question.vote_count
                -elsif question.vote_count > 0
                  %td.align-middle.text-center.bg-success
                    %h3.text-white
                      = question.vote_count
                - else
                  %td.align-middle.text-center
                    %h3.text-secondary
                      = question.vote_count
                %td.align-middle.text-center
                  %h3.text-secondary
                    = question.answers.length
                %td
                  %h5
                    =link_to truncate(question.title, length:70), question
                  %p.text-right= "Hace #{time_ago_in_words(question.created_at.utc.to_i)} por #{question.user.first_name} #{question.user.last_name}"
                  - 0.upto(question.question_tags.size){|index|
                  -  if index>6
                    - break  
                  -  elsif(question.question_tags[index]!=nil)
                    %span.text-primary.tagstyle.p-1.mr-1
                      =question.question_tags[index].tag.name
                  - }
  - elsif @findQuestions == []
    .row.mt-5
      .col-1
      .col-3.text-center.pr-0
        .card.text-white#popular
          %h5.mt-1.font-weight-bold
            Resultados de la búsqueda
    .row.justify-content-center
      .col-10
        .card.imageContainer
          .row.justify-content-center
            .col-6.text-center
              %h5.font-weight-bold.mt-5
                No hubo resultados en la búsqueda
              %img.img-fluid(src="https://d30y9cdsu7xlg0.cloudfront.net/png/1635-200.png" alt="")
              %p
                También puede realizar búsquedas por etiquetas.
  - else
    .row.mt-5
      .col-1
      .col-3.text-center.pr-0
        .card.text-white#popular
          %h5.mt-1.font-weight-bold
            Resultados de la búsqueda
    .row.justify-content-center
      .col-10
        %table.table.table-bordered#popularquestions.bg-white
          %thead
            %tr.text-center
              %td.font-weight-bold Votos
              %td.font-weight-bold Respuestas
              %td.font-weight-bold Título de la pregunta
          %tbody
            - @findQuestions.each do |question|
              %tr
                -if question.vote_count < 0
                  %td.align-middle.text-center.bg-danger
                    %h3.text-white
                      = question.vote_count
                -elsif question.vote_count > 0
                  %td.align-middle.text-center.bg-success
                    %h3.text-white
                      = question.vote_count
                - else
                  %td.align-middle.text-center
                    %h3.text-secondary
                      = question.vote_count
                %td.align-middle.text-center
                  %h3.text-secondary
                    = question.answers.length
                %td
                  %h5
                    =link_to truncate(question.title, length:70), question
                  %p.text-right= "Hace #{time_ago_in_words(question.created_at.utc.to_i)} por #{question.user.first_name} #{question.user.last_name}"
                  - 0.upto(question.question_tags.size)  {|index|
                  -  if index>6
                    - break  
                  -  elsif(question.question_tags[index]!=nil)
                    %span.text-primary.tagstyle.p-1.mr-1
                      =question.question_tags[index].tag.name
                  - }





  

          



  -# %td= link_to 'Show', question_answers_path(question.id)

app/views/questions/new.html.haml
.container
	.row.mt-5
		.col-8
			= render 'form'
		.col-4
			#exampletitle
				.card.p-4.colorexample
					%h5
						¿Cómo preguntar?
					%p
						%strong
							¿Tú pregunta es sobre programación?
					%p
						Preferimos preguntas que pueden ser respondidas, no simplemente debatidas.
					%p
						Proporciona detalles. Comparte lo que ya sabes.
			#examplebody
				.card.p-4.colorexample
					%h5
						¿Cómo formatear?
					%li.mt-2
						Usa saltos de línea para separar párrafos
					%li.mt-2
						Para añadir un salto de línea, coloc 2 espacios al final
					%li.mt-2
						%i
							_cursiva_
						o
						%strong
							**negrita**
					%li.mt-2
						identa el código con 4 espacios
					%li.mt-2
						Las palabras reservadas del código cambian de color
					%li 
						Crea un bloque de cita poniendo > al conmienzo de la línea
			#exampletags
				.card.p-4.colorexample
					%h5
						¿Cómo etiquetar?
					%p
						Una etiqueta es una palabra clave que categoriza su pregunta con otras preguntas similares. Elija una o más etiquetas que ayudarán a los demas usuarios a encontrar e interpretar su pregunta.
					%li
						Completa la oración: mi pregunta es sobre...
					%li
						Use etiquetas que describan cosas o conceptos que son esenciales, no relacionados con su pregunta
					%li
						Lea la descripción que aparece debajo de "Etiquetas"
					%li
						Combine palabras múltiples en palabras sueltas con guiones (por ejemplo, android-studio)
					%li
						Crear nuevas etiquetas es un privilegio; Si su etiqueta no existe, asegurese que esté bien redactada y tenga sentido

					


-# = link_to 'Back', root_path

app/views/questions/show.html.haml
.container
  .max
    %h3.border-bottom.pb-3.max
      = @question.title
  .row.pt-3
    .col-1.text-center
      .row.pt-2
      = link_to(:controller => "questions", :action => "upvote", :id => @question) do
        = icon(@tu_class, 'thumbs-up', class:"text-success")
       
      .row.pt-2
      %h3.text-secondary
        = @question_votes
      .row.pt-0
      = link_to(:controller => "questions", :action => "downvote", :id => @question) do
        = icon(@td_class, 'thumbs-down',class:"text-danger")
    .col-9.max
      = @question.body.html_safe
  .row
    .col-10
    .col-2
      %b User:
      = @question.user.first_name
  = link_to 'Edit', edit_question_path(@question)
  -if @answers.length>0
    %h4.pt-4.border-bottom.pb-3  
      = @answers.length
      - if  @answers.length>1
        Respuestas
      - else 
        Respuesta
    - @answers.each do |answer|
      .row.pt-4    
        .col-1.text-center
          .row.pt-2
            -@vote = Vote.find_by({votable_type: "Answer",votable_id: answer.id,voter_id:current_user.id}) if(current_user)
            -if(@vote)
              -if(@vote.vote_flag)
                -@td_class_answer = 'far'
                -@tu_class_answer = 'fas'
              -else 
                -@td_class_answer = 'fas'
                -@tu_class_answer = 'far'
            -else
              -@td_class_answer = 'far'
              -@tu_class_answer = 'far'
          = link_to(:controller => "answers", :action => "upvote", :question_id => @question,:id => answer) do
            = icon(@tu_class_answer, 'thumbs-up', class:"text-success")
          %h3.text-secondary
            -@answer_votes= Vote.where({votable_type: :Answer, votable_id:answer.id})
            = @answer_votes = @answer_votes.select{|vote| vote.vote_flag}.size - @answer_votes.select{|vote| !vote.vote_flag}.size
          .row.pt-0
          = link_to(:controller => "answers", :action => "downvote", :question_id => @question,:id => answer) do
            = icon(@td_class_answer, 'thumbs-down', class:"text-danger")
          = answer.status
        .col-9 
          = answer.body.html_safe
      .row.border-bottom.pb-3 
        .col-10
        .col-2
          %b User:
          = answer.user.first_name
          -# %td= link_to 'Show', answer
          -# %td= link_to 'Edit', edit_answer_path(answer)
          -# %td= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' }
  %h5.pt-4.border-bottom.pb-3 
    Tu Respuesta
    .row.pt-4
      .col-12
        = render 'formanswer'   