config/routes.rb
Rails.application.routes.draw do

  get 'votes/new'

  get 'votes/create'
 
devise_for :users
root to: "questions#index"
 get 'questions/upvote'
 get 'questions/downvote'
 get 'answers/upvote'
 get 'answers/downvote'
resources :questions do
  resources :answers do
    resources :votes
  end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  has_many :votes, dependent: :destroy
  enum status: { banned: 0, proposed: 1, accepted:2 }
  acts_as_votable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy,:upvote,:downvote]
  before_action :set_question, only: [:upvote, :downvote]
  before_action :authenticate_user!, only: [:create]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
    @question = Question.find(params[:question_id])
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params.merge!({user_id:current_user.id,question:@question}))
    
    respond_to do |format|
      if @answer.save
        format.html { redirect_to @question, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to @question, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @vote=Vote.find_by({votable_type:"Answer",votable_id:@answer.id,voter_id:current_user.id}) if current_user
    if !@vote  && current_user
      current_user.likes @answer
    elsif @vote
      if(@vote.vote_flag)
        @vote.destroy
      else
        @vote.update(vote_flag: true)
      end
    end
    
    redirect_to question_path(@question)
  end

  def downvote
      @vote=Vote.find_by({votable_type:"Answer",votable_id:@answer.id,voter_id:current_user.id}) if current_user
      if !@vote && current_user
        current_user.dislikes @answer
      elsif @vote
        if(!@vote.vote_flag)
          @vote.destroy
        else
          @vote.update(vote_flag:false)
        end 
      end 
       
      redirect_to question_path(@question)
  end 
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end
    def set_question
      @question = Question.find(params[:question_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:status, :body, :user_id, :question_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.haml
= form_for [@question, @answer] do |f|
  - if @answer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@answer.errors.count, "error")} prohibited this answer from being saved:"
      %ul
        - @answer.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :user
    = f.text_field :user_id, :value => params[:user_id]
  .field
    = f.label :question
    = f.text_field :question_id, :value => params[:question_id]
  .actions
    = f.submit 'Save'

app/views/answers/edit.html.haml
%h1 Editing answer

= render 'form'

= link_to 'Show', @answer
\|
= link_to 'Back', answers_path

app/views/answers/index.html.haml
.main
  .header
  .menu
  %input{:onclick => "myTRY()", :type => "button", :value => "RUN"}/
  .content
  #browser
  %textarea#editor
    :preserve

app/views/answers/new.html.haml
%h1 New answer

= render 'form'

-# = link_to 'Back', answers_path

app/views/answers/show.html.haml
%p#notice= notice

%p
  %b Status:
  = @answer.status
%p
  %b Body:
  = @answer.body
%p
  %b User:
  = @answer.user
%p
  %b Question:
  = @answer.question

= link_to 'Edit', edit_answer_path(@answer)
\|
= link_to 'Back', answers_path