config/routes.rb
Rails.application.routes.draw do

  get 'votes/new'

  get 'votes/create'
 
devise_for :users
root to: "questions#index"
 get 'questions/upvote'
 get 'questions/downvote'
 get 'answers/upvote'
 get 'answers/downvote'
resources :questions do
  resources :answers do
    resources :votes
  end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.haml
%nav.row.navbar.navbar-light.p-1{:style => "background-color: #e3f2fd; max-width: 101.2%"}
   %a.navbar-brand.col-2.mr-5.mt-1.ml-2{:href => questions_path}
      %img.d-inline-block.col-6{:alt => "Logo", :src => "/assets/logo.svg", :height => "55px"}
      %p.col-6.d-inline-block.estilodeltitulo.mt-2
         %strong HACK Overflow
   = form_tag root_path, :method => 'get' do
      %p.mt-3
         = text_field_tag :search, params[:search], id:"searchText"
         = submit_tag "Search", :name => nil, id:"searchButton"
   = link_to new_question_path do
      %button.btn.btn-primary.p-2{:type => "button"}
         Formular pregunta
         = icon('fas', 'question')
      
   -if user_signed_in?
      = link_to destroy_user_session_path, method: :delete do
         %button.btn.btn-danger.mr-5.p-2{:type => "button"}
            Cerrar sesion
            = icon('fas', 'sign-out-alt')
   -else 
      = link_to new_user_session_path do
         %button.btn.btn-success.mr-5.p-2{:type => "button"}
            Iniciar sesion
            = icon('fas', 'user-circle')
        
    
    
    
    
  

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title HackOverflow
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css", :rel => "stylesheet"}/
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"} 
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css", :rel => "stylesheet"}/
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"}  
  %body.turbolinks-disable-scroll
    -if devise_controller? 
      = yield
    -else
      = render "layouts/navbar" 
      = yield
      %p.notice= notice
      %p.alert= alert
        
    

      